Logger feature
marceloribeiro/booyah pull request #20
Opened 2023-08-15 21:20 UTC by klaus-trabalhando

It creates if not exists a config.ini with the configuration of log file path and log level, the default will be $root/logs/development.log and DEBUG level.
To use, will just need to import the logger instance and call the methods (info, debug, warn, error), you can pass as many args as you want. ie:
`logger.debug('as', 'many', variable, object, dict, delimiter=', ')`

2023-08-15 23:40 UTC, thauan-andre-clear approved these changes

2023-08-16 05:33 UTC, marceloribeiro commented on src/lib/logger.py
> +DEFAULT_LOG_LEVEL = 'DEBUG'
Can you please set/get the DEFAULT_LOG_LEVEL from the .env file?

2023-08-16 05:34 UTC, marceloribeiro commented on src/lib/logger.py
> +ENV = 'development'
Same here, please get it from the env file, we call it 'BOOYAH_ENV'.

```
os.getenv('BOOYAH_ENV')
```

2023-08-16 05:37 UTC, marceloribeiro commented on src/lib/logger.py
> +        self._log_file_path = Template(config['DEFAULT']['log_file_path']).substitute(environment=ENV, root=base_path)
Is there a reason you're using _ to start the attribute here?

2023-08-16 05:37 UTC, marceloribeiro requested changes
Looks great! Just a few small comments

2023-08-16 11:52 UTC, klaus-trabalhando commented on src/lib/logger.py
> +        self._log_file_path = Template(config['DEFAULT']['log_file_path']).substitute(environment=ENV, root=base_path)
Yes, I added it just to be easy to known where is the log path, you can call print(logger._log_file_path) in any place you imported logger, but it is not really required to use, I can remove it.

2023-08-16 11:54 UTC, klaus-trabalhando commented on src/lib/logger.py
> +DEFAULT_LOG_LEVEL = 'DEBUG'
I will replace it, but I do not have a .env file here, I did not know about it, I will find how and where to create it.

2023-08-16 12:05 UTC, klaus-trabalhando commented on src/lib/logger.py
> +DEFAULT_LOG_LEVEL = 'DEBUG'
do you prefer to use .env directly instead of creating a .ini file? I think it is not needed to have two places to configure. @marceloribeiro

2023-08-16 13:05 UTC, marceloribeiro approved these changes
👍 great work

2023-08-16 13:42 UTC, merged