First generator (controller)
marceloribeiro/booyah pull request #27
Opened 2023-08-18 20:01 UTC by klaus-trabalhando

2023-08-19 07:02 UTC, marceloribeiro requested changes

2023-08-19 07:02 UTC, marceloribeiro commented on bin/lib/generate.py
> +    icon = "❌"
Can you please set this in a constant that is easily accessible/changeable?

2023-08-19 07:02 UTC, marceloribeiro commented on bin/lib/generate.py
> +    icon = "\033[32m✔\033[0m"
Same here, it would fit better in a constant.

2023-08-19 07:02 UTC, marceloribeiro commented on bin/lib/generate.py
> +        print_error(f'controller already exists ({target_file})')
We should ask them if they want to overwrite existing controller.

2023-08-19 07:02 UTC, marceloribeiro commented on bin/lib/generate.py
> +    if args.generate == 'controller':
Same here , it would be good to avoid hardcoded strings in the code, place them in constants makes it easier

2023-08-19 07:02 UTC, marceloribeiro commented on bin/lib/helpers/string_functions.py
> +    return snake_case_name
I see you created a new functions file, can you please move these to the existing application_helper.py? I already have a function there

2023-08-19 07:02 UTC, marceloribeiro commented
Great job overall! thank you

2023-08-21 12:32 UTC, klaus-trabalhando commented on bin/lib/generate.py
> +    icon = "\033[32m✔\033[0m"
done @marceloribeiro

2023-08-21 12:32 UTC, klaus-trabalhando commented on bin/lib/generate.py
> +    if args.generate == 'controller':
done @marceloribeiro

2023-08-21 16:28 UTC, klaus-trabalhando commented on bin/lib/helpers/string_functions.py
> +    return snake_case_name
done

2023-08-21 16:35 UTC, marceloribeiro approved these changes
👍 Good job!

2023-08-21 17:28 UTC, merged