booyah command line - console, server, generators
marceloribeiro/booyah pull request #31
Opened 2023-08-22 19:20 UTC by klaus-trabalhando

2023-08-22 21:31 UTC, marceloribeiro requested changes

2023-08-22 21:31 UTC, marceloribeiro commented on bin/booyah
> +
This funciton main() ended up a bit too big. Maybe it would be easier to split the steps/ifs into functions?

Something like:

def run_g

def run_new

def run_s

def run_c

and call it dinamically like:

```
getattr(f"run_{args.comman}")
```

2023-08-22 21:31 UTC, marceloribeiro commented on bin/booyah
> +def start_server():
It would be nice to have all code inside this function in a class, maybe named 
```
class BooyahServer:
    def run:
```

I think the server itself has a lot of room to evolve, because we will need to handle a bunch of stuff later on like the session, port, etc.

2023-08-22 21:43 UTC, klaus-trabalhando commented on bin/booyah
> +
Nice, I will try it, thanks!

2023-08-22 21:44 UTC, klaus-trabalhando commented on bin/booyah
> +def start_server():
ok, I will improve it

2023-08-22 23:07 UTC, klaus-trabalhando commented on src/server/booyah_runner.py
> +class BooyahRunner:
@marceloribeiro I created this file/class to handle the run_ methods

2023-08-22 23:07 UTC, klaus-trabalhando commented on src/server/booyah_server.py
> +class BooyahServer:
@marceloribeiro I created the BooyahServer class with the run command to start the server

2023-08-23 05:03 UTC, zeitviewmarcelo approved these changes

2023-08-23 05:05 UTC, marceloribeiro approved these changes

2023-08-23 05:05 UTC, merged