Pip structure
marceloribeiro/booyah pull request #32
Opened 2023-08-24 15:58 UTC by klaus-trabalhando

2023-08-24 17:02 UTC, marceloribeiro requested changes
Looks great overall. Just a few comments and some template files that I dont think should be templates...

2023-08-24 17:02 UTC, marceloribeiro commented on .gitignore
I added dist/ to my .gitignore. Can you please remove the dist folder, add it to your git ignore, so that we dont push dist files? We dont need to push them

2023-08-24 17:02 UTC, marceloribeiro commented on src/.booyah_version
> +0.0.3
Is this outdated? Looks like we are at 0.0.12?

2023-08-24 17:02 UTC, marceloribeiro commented on src/booyah/.booyah_version
> +0.0.3
same, outdated version?

2023-08-24 17:02 UTC, marceloribeiro commented on src/booyah/generators/console.py
> -current_dir = os.path.dirname(os.path.abspath(__file__))
would it be too complex to get the console out of 'generators'? It's not really a generator...

2023-08-24 17:02 UTC, marceloribeiro commented on src/booyah/generators/templates/generate_new/db/adapters/base_adapter.py
> +import os
why is this file a template? it should not be part of the project, but rather part of booyah package.

2023-08-24 17:02 UTC, marceloribeiro commented on src/booyah/generators/templates/generate_new/db/adapters/postgresql_adapter.py
> +import psycopg
why is this file a template? it should not be part of the project, but rather part of booyah package.

2023-08-24 17:02 UTC, marceloribeiro commented on src/booyah/generators/templates/generate_new/config/routes.py
> +from booyah.router.application_router import ApplicationRouter
why is this file a template? it should not be part of the project, but rather part of booyah package.

2023-08-24 17:13 UTC, klaus-trabalhando commented on .gitignore
Ok

2023-08-24 17:14 UTC, klaus-trabalhando commented on src/.booyah_version
> +0.0.3
I forgot to remove this file, it is not been used anymore, when we package to pip, it does not copy files with dot prefix, like .env or .booyah_version, I am now creating this file by parsing the result of pip show booyah

2023-08-24 17:20 UTC, klaus-trabalhando commented on src/booyah/generators/templates/generate_new/db/adapters/base_adapter.py
> +import os
Some folders I moved to templates just to make the server to work, I will remove it

2023-08-24 17:20 UTC, klaus-trabalhando commented on src/booyah/generators/templates/generate_new/db/adapters/postgresql_adapter.py
> +import psycopg
Just added to work booyah s, I will remove it

2023-08-24 17:21 UTC, klaus-trabalhando commented on src/booyah/generators/templates/generate_new/config/routes.py
> +from booyah.router.application_router import ApplicationRouter
Just added to work booyah s, I will remove it

2023-08-25 12:19 UTC, marceloribeiro approved these changes
👍 looks great

2023-08-25 12:23 UTC, merged