Booyah 30/setup database migrations
marceloribeiro/booyah pull request #34
Opened 2023-08-27 18:11 UTC by marceloribeiro

2023-08-28 13:04 UTC, klaus-trabalhando requested changes

2023-08-28 13:04 UTC, klaus-trabalhando commented on src/booyah/db/adapters/base_adapter.py
> +        adapter_class = to_camel_case(adapter + '_adapter')
Maybe you should import the Strings extension and use it instead of  to_camel_case()

2023-08-28 13:04 UTC, klaus-trabalhando commented on src/booyah/db/adapters/postgresql/postgresql_schema_helper.py
> +    def create_table(self, table_name, table_columns, force=False):
I think the force argument is doing the opposite of the expected, when set force to True, I expect to ignore if already exists, or maybe replace it if already exists, I think you can change the argument name to ignoreIfExists to be easy to understand or change the if condition to the opposite

2023-08-28 13:04 UTC, klaus-trabalhando commented on src/booyah/db/adapters/postgresql/postgresql_schema_helper.py
> +        self.adapter.execute(f"ALTER TABLE {table_name} DROP COLUMN {column_name}", False)
You can Drop column if exists too, like the drop table.

2023-08-28 13:04 UTC, klaus-trabalhando commented on src/booyah/db/adapters/postgresql/postgresql_schema_helper.py
> +        self.adapter.execute(f"CREATE INDEX {table_name}_{column_name}_index ON {table_name} ({column_name})", False)
Maybe you could have an optional param for index name and to change the column_name to column_names allowing to set an array of columns to be indexed together

2023-08-28 13:04 UTC, klaus-trabalhando commented on src/booyah/db/adapters/postgresql/postgresql_schema_helper.py
> +    def remove_index(self, table_name, column_name):
Same here, should be able to remove by index name or table + column_names

2023-08-28 13:04 UTC, klaus-trabalhando commented on src/booyah/db/migrate/application_migration.py
> +        return migrations
Maybe you should sort the migration files before return it, migrations should be run following the file names (timestamp prefix used to ensure the correct order)

2023-08-28 13:04 UTC, klaus-trabalhando commented on src/booyah/db/migrate/application_migration.py
> +        migrations.sort()
Maybe it could be sorted inside the get_migrations() method

2023-08-28 13:04 UTC, klaus-trabalhando commented on src/booyah/generators/templates/migration
> +        super().up(lambda: self.adapter.create_table('%{table_name}%', %{fields}%))
is the migration template really needed? cause it has a create_table hardcoded, maybe it should be like:
```
def up(self):
    %{up_content}%

def down(self):
    %{down_content}%
```

2023-08-30 11:25 UTC, marceloribeiro commented on src/booyah/db/adapters/base_adapter.py
> +        adapter_class = to_camel_case(adapter + '_adapter')
@klaus-trabalhando this is solved

2023-08-30 11:25 UTC, marceloribeiro commented on src/booyah/db/adapters/postgresql/postgresql_schema_helper.py
> +    def create_table(self, table_name, table_columns, force=False):
@klaus-trabalhando I am actually using IF NOT EXISTS so the flag should be fine:

if force=True, create table
if force=False, create table if not exists

2023-08-30 11:25 UTC, marceloribeiro commented on src/booyah/db/adapters/postgresql/postgresql_schema_helper.py
> +        self.adapter.execute(f"CREATE INDEX {table_name}_{column_name}_index ON {table_name} ({column_name})", False)
@klaus-trabalhando nice suggestion, I've done it.

2023-08-30 11:26 UTC, marceloribeiro commented on src/booyah/db/adapters/postgresql/postgresql_schema_helper.py
> +    def remove_index(self, table_name, column_name):
@klaus-trabalhando done

2023-08-30 11:26 UTC, marceloribeiro commented on src/booyah/db/migrate/application_migration.py
> +        return migrations
@klaus-trabalhando done

2023-08-30 11:26 UTC, marceloribeiro commented on src/booyah/generators/templates/migration
> +        super().up(lambda: self.adapter.create_table('%{table_name}%', %{fields}%))
@klaus-trabalhando done

2023-08-30 11:26 UTC, marceloribeiro commented on src/booyah/db/migrate/application_migration.py
> +        migrations.sort()
@klaus-trabalhando done

2023-08-30 11:26 UTC, marceloribeiro commented on src/booyah/db/adapters/postgresql/postgresql_schema_helper.py
> +        self.adapter.execute(f"ALTER TABLE {table_name} DROP COLUMN {column_name}", False)
@klaus-trabalhando I'd rather not, because if they create a bad migration we want it to fail. I.e. try to drop a column that is not there, it should fail so they know something is wrong

2023-08-30 12:25 UTC, klaus-trabalhando requested changes

2023-08-30 12:25 UTC, klaus-trabalhando commented on src/booyah/db/adapters/base_adapter.py
> +        adapter_class = String(adapter + '_adapter').camelize()
I think you could just call (adapter + '_adapter').camelize(), the left variable String will handle the join to return String
```
>>> a = String('adapter')
>>> (a + '_adapter').camelize()
'AdapterAdapter'
```

2023-08-30 12:25 UTC, klaus-trabalhando commented on src/booyah/db/adapters/postgresql/postgresql_schema_helper.py
> +        if force:
Here should be the opposite: if force: then create table if not exists, to not raise an error

2023-08-30 12:37 UTC, marceloribeiro commented on src/booyah/db/adapters/base_adapter.py
> +        adapter_class = String(adapter + '_adapter').camelize()
@klaus-trabalhando done

2023-08-30 12:38 UTC, marceloribeiro commented on src/booyah/db/adapters/postgresql/postgresql_schema_helper.py
> +        if force:
@klaus-trabalhando done

2023-08-30 12:48 UTC, klaus-trabalhando approved these changes

2023-08-30 12:49 UTC, merged