Forms support
marceloribeiro/booyah pull request #37
Opened 2023-08-30 20:03 UTC by klaus-trabalhando

2023-08-30 23:33 UTC, marceloribeiro requested changes

2023-08-30 23:33 UTC, marceloribeiro commented on src/booyah/controllers/application_controller.py
> +    def __init__(self, environment, load_params=True):
I think we should stick with the convention of method names without the underscore starting. if the argument coming in the function is what's causing you to create a _load_params() method, maybe the argument name should be 'should_load_params' so that the method can stay load_params9)

2023-08-30 23:33 UTC, marceloribeiro commented on src/booyah/controllers/application_controller.py
> +    def __parse_nested_attributes(self, data):
same here, can we stick with method names with no underscores?

2023-08-30 23:33 UTC, marceloribeiro commented on src/tests/lib/controllers/application_controller_test.py
Can you please add a test case for the newly added parse_nested_attributes method? It would be good to have a test case demonstrating how it works, how data comes in and how it comes out

2023-08-30 23:33 UTC, marceloribeiro commented on src/booyah/controllers/application_controller.py
> +            elif content_type == 'application/x-www-form-urlencoded':
Can you pleaase move the application/x-.... string to a constant?

2023-08-30 23:33 UTC, marceloribeiro commented on src/booyah/controllers/application_controller.py
> +            elif 'multipart/form-data' in content_type:
same here please move the string to a constant

2023-08-30 23:33 UTC, marceloribeiro commented on src/booyah/generators/templates/generate_new/app/controllers/application_controller.py
> +from booyah.controllers.application_controller import ApplicationController as BooyahApplicationController
I think maybe it would be better to just rename the application_controller inside booyah package to BooyahApplicationController by default so we dont need to alias here

2023-08-30 23:33 UTC, marceloribeiro commented on src/booyah/models/application_model.py
> +            if self.table_columns:
do we need this if? maybe we could just sort directly

2023-08-30 23:33 UTC, marceloribeiro commented on src/booyah/response/application_response.py
> +    def __init__(self, environment, data = {}, headers = [], status = DEFAULT_HTTP_STATUS):
I've never seen headers as an array, always as a hash. Any reason you're changing it here?

2023-08-30 23:33 UTC, marceloribeiro commented on src/booyah/router/application_router.py
> +        for route in self.routes:
I think we should not be running the same loop twice. One way to maybe solve this is to turn the array of routes into a key => value hash where key is the path and the value is the entire route object. That way we could try a exact match by doing something like ```routes_dict[self.path]``` or something

2023-08-30 23:33 UTC, marceloribeiro commented on src/booyah/templates/users/edit.html
> +    document.getElementById("putForm").addEventListener("submit", function(event) {
Ok, so it needs to work with plain html, not the help of js code. Normally just a form tag with a input type="submit" should do.  If you need the js to override the method (POST-PUT) then the js needs to be outside the template. Rails normally creates an application.js where it would import other js files to take care of things like these.

2023-08-30 23:33 UTC, marceloribeiro commented on src/booyah/templates/users/index.html
> +    var deleteForms = document.getElementsByClassName("deleteForm");
In this case, I understand you're building the form to get the effect of a DELETE. But this should be in a js file outside of the html code, imported with the script tag, etc. Imagine when we have 10 lists of different models, we'd end up with tons of duplicated js.

2023-08-30 23:33 UTC, marceloribeiro commented on src/tests/requests/users.py
> +
can you please rename it so it ends with _test.py like every test?

2023-08-30 23:33 UTC, marceloribeiro commented on src/tests/requests/users.py
> +class UsersControllerRequests:
We should follow the pattern of addint Test before the class name. Also it is not clear to me which methods are test methods here, but test methods need to start with test_

2023-08-30 23:33 UTC, marceloribeiro commented on src/tests/requests/users.py
> +        if self.request_format == 'data':
Maybe it would be best to change 'data' to 'form_data' as it is more obvious what kind of data we're talking about.

2023-08-30 23:33 UTC, marceloribeiro commented on src/tests/requests/users.py
> +    def execute_all(self):
Can you please create each test separately?

```
def test_get_request:
...
```

```
def test_post_request:
...
```

Also, we need to do standard test assertions, like:

```
assert response.status_code == 200
assert response.body == expected_body
```

2023-08-30 23:33 UTC, marceloribeiro commented on src/tests/requests/users.py
> +if __name__ == "__main__":
I dont think you need these if you add test_ to each method. pytest will run them

2023-08-30 23:33 UTC, marceloribeiro commented on src/tests/requests/users.py
> +    def get_request(self):
I have a feeling these are helper methods that should be in a different helper file, imported by all tests. Specially when we start generating scaffolds which will generate controller, model, migration, and: tests

2023-08-31 12:13 UTC, klaus-trabalhando commented on src/booyah/controllers/application_controller.py
> +    def __init__(self, environment, load_params=True):
I agree

2023-08-31 12:14 UTC, klaus-trabalhando commented on src/booyah/controllers/application_controller.py
> +    def __parse_nested_attributes(self, data):
I will remove it, I used the underscore because it is a private method that should not be usefull for the classes who extend it

2023-08-31 12:22 UTC, klaus-trabalhando commented on src/tests/lib/controllers/application_controller_test.py
yes, I will create it

2023-08-31 12:23 UTC, klaus-trabalhando commented on src/booyah/controllers/application_controller.py
> +            elif content_type == 'application/x-www-form-urlencoded':
ok

2023-08-31 12:23 UTC, klaus-trabalhando commented on src/booyah/controllers/application_controller.py
> +            elif 'multipart/form-data' in content_type:
ok

2023-08-31 12:25 UTC, klaus-trabalhando commented on src/tests/requests/users.py
> +class UsersControllerRequests:
that was an internal test cause I didn't know how to test with pytest, I keep it cause it is a good example to simulate RestClient like rails. It will not be imported to pip cause the requests folder has no __init__.py file

2023-09-01 12:13 UTC, klaus-trabalhando commented on src/booyah/response/application_response.py
> +    def __init__(self, environment, data = {}, headers = [], status = DEFAULT_HTTP_STATUS):
Yes, in fact it is an array, I don't know why, I also had problems thinking it was a dict like in the initialization
https://docs.gunicorn.org/en/stable/run.html
```
    def response_headers(self):
        if (self.headers != []):
            return self.headers
        else:
            return [
              ('Content-type', self.environment.get('CONTENT_TYPE', self.DEFAULT_CONTENT_TYPE)),
              ('Content-Length', str(len(self.body)))
            ]
```

2023-09-01 12:47 UTC, klaus-trabalhando commented on src/booyah/router/application_router.py
> +        for route in self.routes:
That will be solved in a new Issue to reformulate routes file

2023-09-01 12:55 UTC, klaus-trabalhando commented on src/booyah/templates/users/edit.html
> +    document.getElementById("putForm").addEventListener("submit", function(event) {
The javascript framework implementation will be created in a new issue.

2023-09-01 12:56 UTC, klaus-trabalhando commented on src/booyah/templates/users/index.html
> +    var deleteForms = document.getElementsByClassName("deleteForm");
The javascript framework implementation will be created in a new issue.

2023-09-01 13:27 UTC, marceloribeiro approved these changes
👍 nice work

2023-09-01 13:34 UTC, merged