Migration up down
marceloribeiro/booyah pull request #58
Opened 2023-09-13 21:36 UTC by klaus-trabalhando

2023-09-16 17:22 UTC, marceloribeiro requested changes

2023-09-16 17:22 UTC, marceloribeiro commented on src/booyah/db/adapters/base_adapter.py
> +
I see you moved a bunch of methods from the postgresql adapter to the base adapter. We should avoid doing this because sometimes the SQL is specific to the database. The BaseAdapter should be free of SQL commands.

2023-09-16 17:22 UTC, marceloribeiro commented on src/booyah/db/adapters/postgresql/postgresql_adapter.py
> +    def execute(self, query, expect_result=True, log_query=True):
I think we should not have log_query as an argument here. the query should always (or never) be logged, depending on the logger level. If debug level is active, the queries will be logged. Otherwise, they wont.

2023-09-16 20:23 UTC, klaus-trabalhando commented on src/booyah/db/adapters/base_adapter.py
> +
The methods I have moved , in fact, need to be converted to use sql builder, select(fields), order(...), limit(...), and it should work fine for all adapters, the table and fields names/types will be the same for all adapters, and if we put this methods in each adapter should not make sense if we can have the query builder for that.

2023-09-16 20:26 UTC, klaus-trabalhando commented on src/booyah/db/adapters/postgresql/postgresql_adapter.py
> +    def execute(self, query, expect_result=True, log_query=True):
I put this argument here cause the execute method is been executed by other method, so the logger was duplicated. Like the insert method, wants to change the color to green, but uses the execute method, it was appearing in green and blue the same log.
```
    def insert(self, table_name, attributes):
        if attributes.get('created_at') is None:
            attributes['created_at'] = datetime.now()
        if attributes.get('updated_at') is None:
            attributes['updated_at'] = datetime.now()
        self.format_attributes(attributes)

        columns = ', '.join(attributes.keys())
        values = ', '.join([f"{value}" for value in attributes.values()])
        query = f"INSERT INTO {table_name} ({columns}) VALUES ({values}) RETURNING id, created_at, updated_at"
        logger.debug("DB:", query, color='green', bold=True)
        return self.execute(query, log_query=False)
```

2023-09-16 20:29 UTC, klaus-trabalhando commented on src/booyah/db/adapters/base_adapter.py
> +
I did not use the sql builder cause I was not focusing in this problem when I moved the method. I was only thinking about organizing the code in a better way.

2023-09-16 21:43 UTC, marceloribeiro commented on src/booyah/db/adapters/base_adapter.py
> +
I dont think we need these query builder methods for simple migration checks, since this is the only table in the db that does not represent a model (no id, no timestamps, etc). it's just about setting the migrations that have been run so it could be delegated for the actual db adapter to run raw sql

2023-09-16 21:45 UTC, marceloribeiro commented on src/booyah/db/adapters/postgresql/postgresql_adapter.py
> +    def execute(self, query, expect_result=True, log_query=True):
I think it gets  a bit ugly to have to add this argument to this and all other functions. In fact, if execute is running the log, the insert doesnt have to do it. As for the color, if you want to use different colors for insert/select then maybe make the execute smarter to find out the color based on the query it is running.  (if the query has 'INSERT' in it, make it blue, etc)

2023-09-17 07:18 UTC, marceloribeiro approved these changes

2023-09-17 07:24 UTC, merged