Attachment s3
marceloribeiro/booyah pull request #68
Opened 2023-10-24 12:57 UTC by klaus-trabalhando

2023-10-26 16:58 UTC, marceloribeiro requested changes

2023-10-26 16:58 UTC, marceloribeiro commented on src/booyah/generators/base_generator.py
> +            return f'{self.attachment_config_prefix(model_name, name)} bucket=\'{bucket}\')'
Why do you have all these attachment related methods in the base generator? It feels they belong somewhere else related to attachment only. Maybe an AttachmentGenerator.

2023-10-26 16:58 UTC, marceloribeiro commented on src/booyah/models/application_model.py
> +            dicttionary = self.__class__.find(self.id).to_dict()
dicttionary doesnt have 2 't's. if it is a reserved word maybe used something different like att_dictionary

2023-10-26 16:58 UTC, marceloribeiro commented on src/booyah/models/booyah_attachment.py
> +        self.record_id = self.record_id if self.record_id else self.record.id
dont you need to set record_type?

2023-10-26 16:58 UTC, marceloribeiro commented on src/booyah/models/booyah_attachment.py
> +        self.record_id = self.record_id if self.record_id else self.record.id
dont you need to set record_type?

2023-10-26 16:58 UTC, marceloribeiro commented on src/booyah/models/booyah_attachment.py
> +        for bucket in session.resource('s3').buckets.all():
Im worried about this line.... looping through all buckets? just to get the one with the name? I think it's not our responsibility to tell them the bucket doesnt exist. If it fails the upload, we just use the error message that the bucket doesnt exist.

2023-10-26 16:58 UTC, marceloribeiro commented on src/booyah/models/booyah_attachment.py
> +    method1 = types.FunctionType(
'method1' doesnt really translate what this is about, maybe there is a better name?

2023-10-26 20:26 UTC, klaus-trabalhando commented on src/booyah/generators/base_generator.py
> +            return f'{self.attachment_config_prefix(model_name, name)} bucket=\'{bucket}\')'
because I need this data in more than one generator, like model/scaffold/migrate generator. So you can call booyah g scaffold user photo:image, or booyah g model photo:image, or booyah g migration add_photo_to_users photo:image.

2023-10-26 20:27 UTC, klaus-trabalhando commented on src/booyah/models/application_model.py
> +            dicttionary = self.__class__.find(self.id).to_dict()
sorry, I only copied this part of the code from another function. I also noted this error, but I though that should have some reason.

2023-10-26 20:34 UTC, klaus-trabalhando commented on src/booyah/models/booyah_attachment.py
> +        self.record_id = self.record_id if self.record_id else self.record.id
Not in this case, the record_type is always present. It is related to the parent model like User that should be or not a new_record, so if it is a new record, self.record_id can be blank, but the self.record(the user object reference).id is present, the record_type is set for either new record and existent record automatically.

2023-10-26 20:36 UTC, klaus-trabalhando commented on src/booyah/models/booyah_attachment.py
> +        self.record_id = self.record_id if self.record_id else self.record.id
No, it is automatically set. I am not sure if the "update" need this condition too, cause the record should already exist for doing an update.

2023-10-26 20:39 UTC, klaus-trabalhando commented on src/booyah/models/booyah_attachment.py
> +        for bucket in session.resource('s3').buckets.all():
I agree with that, but this condition will run only once per model since it is an static instance, but you are right, it is not really necessary and can consumpt some time to run.

2023-10-26 20:39 UTC, klaus-trabalhando commented on src/booyah/models/booyah_attachment.py
> +    method1 = types.FunctionType(
Yeah

2023-12-11 11:05 UTC, marceloribeiro approved these changes
👍 nice work, we finally get to release attachments! thank you

2023-12-11 12:16 UTC, merged